//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Otomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int CommentId { get; set; }
        public short RoomId { get; set; }
        public string Description { get; set; }
        public string NameSurname { get; set; }
        public string IconUrl { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
